name: auto-publish

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # RSS feed should have accurate timezone
      - name: Update timezone
        uses: zcong1993/setup-timezone@v2.0.0
        with:
          timezone: Asia/Seoul
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install
        run: python -m pip install --upgrade pip baku
      - name: Build blog
        run: |
          baku --build
          TEMP=`mktemp -d`
          cp -r html/* $TEMP
          echo "temp=$TEMP" >> $GITHUB_ENV
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Update
        run: |
          rm -rf ./*
          cp -r ${{ env.temp }}/* .
          touch .nojekyll
      - name: Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *
          git commit -m "Blog rebuild"
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
